import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { FiLock } from 'react-icons/fi';
import { orderAPI } from '../services/api';
import { useCart } from '../context/CartContext';
import { useAuth } from '../context/AuthContext';
import toast from 'react-hot-toast';

const CheckoutPage = () => {
    const { cart, fetchCart } = useCart();
    const { user } = useAuth();
    const navigate = useNavigate();
    const [loading, setLoading] = useState(false);
    const [form, setForm] = useState({
        shippingName: user?.name || '',
        shippingAddress: '',
        shippingCity: '',
        shippingState: '',
        shippingZip: '',
        shippingPhone: '',
    });

    const handleChange = (e) => {
        setForm(prev => ({ ...prev, [e.target.name]: e.target.value }));
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        if (cart.items.length === 0) {
            toast.error('Your cart is empty');
            return;
        }
        setLoading(true);
        try {
            const response = await orderAPI.checkout(form);
            const checkoutData = response.data.data;
            const razorpayOrderId = checkoutData.checkoutUrl; // Renamed from backend
            
            const options = {
                key: 'rzp_test_SUPBzaVmVYZfqM', 
                amount: cart.totalAmount * 100,
                currency: 'INR',
                name: 'ShopEase',
                description: 'Order Payment',
                order_id: razorpayOrderId,
                handler: function (response) {
                    // Send to success page with razorpay order id
                    // Actually, razorpay_order_id matches the one generated by backend
                    window.location.href = `/order-success?session_id=${response.razorpay_order_id}`;
                },
                prefill: {
                    name: form.shippingName,
                    email: user?.email || '',
                    contact: form.shippingPhone
                },
                theme: {
                    color: '#22c55e'
                }
            };

            const rzp = new window.Razorpay(options);
            rzp.on('payment.failed', function (response){
                toast.error(response.error.description || 'Payment failed');
                setLoading(false);
            });
            rzp.open();
        } catch (error) {
            toast.error(error.response?.data?.message || 'Checkout failed');
            setLoading(false);
        }
    };

    if (cart.items.length === 0) {
        navigate('/cart');
        return null;
    }

    return (
        <div className="checkout-page">
            <h1 className="page-title">Checkout</h1>

            <form className="checkout-form" onSubmit={handleSubmit}>
                <h2>Shipping Information</h2>

                <div className="form-group">
                    <label htmlFor="shippingName">Full Name</label>
                    <input
                        id="shippingName"
                        name="shippingName"
                        type="text"
                        value={form.shippingName}
                        onChange={handleChange}
                        required
                        placeholder="John Doe"
                    />
                </div>

                <div className="form-group">
                    <label htmlFor="shippingAddress">Street Address</label>
                    <input
                        id="shippingAddress"
                        name="shippingAddress"
                        type="text"
                        value={form.shippingAddress}
                        onChange={handleChange}
                        required
                        placeholder="123 Main Street"
                    />
                </div>

                <div className="form-row">
                    <div className="form-group">
                        <label htmlFor="shippingCity">City</label>
                        <input
                            id="shippingCity"
                            name="shippingCity"
                            type="text"
                            value={form.shippingCity}
                            onChange={handleChange}
                            required
                            placeholder="New York"
                        />
                    </div>
                    <div className="form-group">
                        <label htmlFor="shippingState">State</label>
                        <input
                            id="shippingState"
                            name="shippingState"
                            type="text"
                            value={form.shippingState}
                            onChange={handleChange}
                            required
                            placeholder="NY"
                        />
                    </div>
                </div>

                <div className="form-row">
                    <div className="form-group">
                        <label htmlFor="shippingZip">ZIP Code</label>
                        <input
                            id="shippingZip"
                            name="shippingZip"
                            type="text"
                            value={form.shippingZip}
                            onChange={handleChange}
                            required
                            placeholder="10001"
                        />
                    </div>
                    <div className="form-group">
                        <label htmlFor="shippingPhone">Phone</label>
                        <input
                            id="shippingPhone"
                            name="shippingPhone"
                            type="tel"
                            value={form.shippingPhone}
                            onChange={handleChange}
                            required
                            placeholder="(555) 123-4567"
                        />
                    </div>
                </div>

                <div style={{
                    padding: 20, background: 'var(--gray-50)', borderRadius: 'var(--radius-md)',
                    marginTop: 24, marginBottom: 24
                }}>
                    <h3 style={{ fontSize: '1rem', fontWeight: 600, marginBottom: 12 }}>Order Summary</h3>
                    {cart.items.map(item => (
                        <div key={item.id} style={{
                            display: 'flex', justifyContent: 'space-between',
                            padding: '8px 0', fontSize: '0.9rem'
                        }}>
                            <span>{item.productName} × {item.quantity}</span>
                            <span style={{ fontWeight: 600 }}>₹{item.subtotal?.toFixed(2)}</span>
                        </div>
                    ))}
                    <div style={{
                        display: 'flex', justifyContent: 'space-between',
                        paddingTop: 12, marginTop: 12, borderTop: '1px solid var(--border)',
                        fontWeight: 700, fontSize: '1.05rem'
                    }}>
                        <span>Total</span>
                        <span>₹{cart.totalAmount?.toFixed(2)}</span>
                    </div>
                </div>

                <button
                    type="submit"
                    className="btn btn-primary btn-lg"
                    style={{ width: '100%' }}
                    disabled={loading}
                >
                    <FiLock />
                    {loading ? 'Processing...' : `Pay ₹${cart.totalAmount?.toFixed(2)} with Razorpay`}
                </button>

                <p style={{
                    textAlign: 'center', fontSize: '0.8rem', color: 'var(--text-muted)',
                    marginTop: 12, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 4
                }}>
                    <FiLock size={12} /> Secure checkout powered by Razorpay
                </p>
            </form>
        </div>
    );
};

export default CheckoutPage;
